# lib/build-sandbox.nix
#
# Assembles a rootfs directory from a NixOS system closure.
# The output directory can be converted to a SIF image.
{
  runCommand,
  closureInfo,
  bashInteractive,
  coreutils,
  nix,
  lib,
  jq,
}:

{
  # The NixOS system configuration (evaluated)
  nixosConfig,
  # Version string for labels.json
  version ? "dev",
}:

let
  toplevel = nixosConfig.config.system.build.toplevel;
  etc = nixosConfig.config.system.build.etc;
  systemPath = nixosConfig.config.system.path;

  closure = closureInfo { rootPaths = [ toplevel ]; };
in
runCommand "nix-apptainer-sandbox"
  {
    __structuredAttrs = true;
    unsafeDiscardReferences.out = true;
    nativeBuildInputs = [
      jq
      coreutils
    ];

    passthru = {
      inherit toplevel etc closure;
    };
  }
  ''
    sandbox=$out

    # Create base directory structure
    mkdir -p $sandbox/{bin,sbin,usr/bin,dev,proc,sys,tmp,var/tmp,run,root}
    mkdir -p $sandbox/home/nixuser
    mkdir -p $sandbox/nix/store/.links
    mkdir -p $sandbox/nix/var/nix/{db,profiles,gcroots/auto,temproots,builds}

    # Copy the entire Nix store closure
    while IFS= read -r storePath; do
      cp -a "$storePath" "$sandbox$storePath"
    done < ${closure}/store-paths

    # Copy nix-path-registration for DB init at first run
    cp ${closure}/registration $sandbox/nix-path-registration

    # Set up /etc from the NixOS etc derivation
    # The etc derivation produces a tree of symlinks into /nix/store
    mkdir -p $sandbox/etc
    if [ -d "${etc}/etc" ]; then
      cp -a ${etc}/etc/* $sandbox/etc/ || true
    fi

    # Ensure critical /etc files exist
    # (Apptainer will overlay /etc/passwd and /etc/group at runtime,
    #  but they're needd in the image for tools that check during build)
    if [ ! -e "$sandbox/etc/passwd" ]; then
      cat > $sandbox/etc/passwd <<'PASSWD'
    root:x:0:0:root:/root:/bin/sh
    nixuser:x:1000:1000:Nix User:/home/nixuser:/bin/sh
    nobody:x:65534:65534:Nobody:/var/empty:/bin/false
    PASSWD
    fi

    if [ ! -e "$sandbox/etc/group" ]; then
      cat > $sandbox/etc/group <<'GROUP'
    root:x:0:
    nixuser:x:1000:
    nogroup:x:65534:
    GROUP
    fi

    ln -s ${bashInteractive}/bin/bash $sandbox/bin/sh
    ln -s ${bashInteractive}/bin/bash $sandbox/bin/bash
    ln -s ${coreutils}/bin/env $sandbox/usr/bin/env

    ln -s ${toplevel} $sandbox/run/current-system

    # System PATH — the NixOS system.path (merged environment.systemPackages)
    mkdir -p $sandbox/usr/local
    ln -s ${systemPath} $sandbox/run/sw

    # Nix binary itself (for single-user use inside the container)
    mkdir -p $sandbox/usr/local/bin
    ln -s ${nix}/bin/nix $sandbox/usr/local/bin/nix
    ln -s ${nix}/bin/nix-store $sandbox/usr/local/bin/nix-store
    ln -s ${nix}/bin/nix-env $sandbox/usr/local/bin/nix-env
    ln -s ${nix}/bin/nix-build $sandbox/usr/local/bin/nix-build
    ln -s ${nix}/bin/nix-channel $sandbox/usr/local/bin/nix-channel
    ln -s ${nix}/bin/nix-collect-garbage $sandbox/usr/local/bin/nix-collect-garbage
    ln -s ${nix}/bin/nix-instantiate $sandbox/usr/local/bin/nix-instantiate

    # nix.conf is already generated by NixOS from nix.settings
    # and copied above via the etc derivation — no need to duplicate

    # .singularity.d metadata for Apptainer
    mkdir -p $sandbox/.singularity.d/env

    cp ${../scripts/entrypoint.sh} $sandbox/.singularity.d/runscript
    chmod +x $sandbox/.singularity.d/runscript

    cat > $sandbox/.singularity.d/env/90-environment.sh <<'ENV'
    #!/bin/sh
    export PATH="/usr/local/bin:/run/sw/bin:/bin:/usr/bin:$PATH"
    export NIX_REMOTE=""
    export LOCALE_ARCHIVE="/run/sw/lib/locale/locale-archive"
    export TERMINFO_DIRS="/run/sw/share/terminfo"
    ENV
    chmod +x $sandbox/.singularity.d/env/90-environment.sh

    jq -n \
      --arg version "${version}" \
      '{
        "org.label-schema.schema-version": "1.0",
        "org.label-schema.name": "nix-apptainer",
        "org.label-schema.version": $version,
        "org.label-schema.description": "Minimal NixOS container with single-user Nix for HPC"
      }' > $sandbox/.singularity.d/labels.json
  ''
